openapi: 3.2.0
info:
  title: FIS® Accounting Data as a Service™ Vendor Controller V2 API
  description: What's changed in our API
  version: v2
  contact: {}
servers:
- url: https://api.railz.ai
  description: Main (production) API server
tags:
- name: VendorControllerV2
paths:
  /v2/accounting/vendors:
    get:
      description: '**Supported for:**


        `freshbooks` `quickbooks` `quickbooksDesktop` `xero` `oracleNetsuite` `sageBusinessCloud` `sageIntacct` `dynamicsBusinessCentral` `dynamics365Finance` `wave` `myob` `zohoBooks`'
      operationId: vendors
      parameters:
      - name: connectionUuid
        required: true
        in: query
        description: Unique connection identifier.
        schema:
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
          type: string
      - name: offset
        required: false
        in: query
        description: The offset is the position in the dataset of a particular record.
        schema:
          format: integer
          type: number
      - name: limit
        required: false
        in: query
        description: 'This is the size of the results set you would like (default: 100).'
        schema:
          format: integer
          example: 100
          type: number
      - name: orderBy
        required: false
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVendorResponseV2Dto'
        '202':
          description: Data in pending state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVendorResponseV2Dto'
        '204':
          description: No data available
        '400':
          description: Bad Request Error - Thrown if fields sent via query does not follow specifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400ResponseDtoV2'
        '401':
          description: Unauthorized - Not logged in or log in expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401ResponseDto'
        '403':
          description: Forbidden - Not enough permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403ResponseDto'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500ResponseDto'
      security:
      - bearer: []
      summary: List Vendors
      tags:
      - VendorControllerV2
    post:
      description: '**Supported for:**


        `freshbooks` `quickbooks` `xero` `oracleNetsuite` `sageBusinessCloud` `sageIntacct` `dynamicsBusinessCentral` `myob` `zohoBooks`'
      operationId: push-vendors
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushVendorV2Dto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PushVendorV2ResponseDto'
        '400':
          description: Bad Request Error - Thrown if fields sent via query does not follow specifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400ResponseDtoV2'
        '401':
          description: Unauthorized - Not logged in or log in expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401ResponseDto'
        '403':
          description: Forbidden - Not enough permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403ResponseDto'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500ResponseDto'
      security:
      - bearer: []
      summary: Create a Vendor
      tags:
      - VendorControllerV2
  /v2/accounting/vendors/batch:
    post:
      description: '**Supported for:**


        `freshbooks` `quickbooks` `xero` `oracleNetsuite` `sageBusinessCloud` `sageIntacct` `dynamicsBusinessCentral`'
      operationId: push-batchVendors
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchPushVendorV2Dto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchPushVendorResponseV2Dto'
        '400':
          description: Bad Request Error - Thrown if fields sent via query does not follow specifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400ResponseDtoV2'
        '401':
          description: Unauthorized - Not logged in or log in expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401ResponseDto'
        '403':
          description: Forbidden - Not enough permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403ResponseDto'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500ResponseDto'
      security:
      - bearer: []
      summary: Batch Create Vendors
      tags:
      - VendorControllerV2
    put:
      description: '**Supported for:**


        `freshbooks` `quickbooks` `xero` `oracleNetsuite` `sageBusinessCloud` `sageIntacct` `dynamicsBusinessCentral`'
      operationId: update-batchVendors
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchUpdateVendorV2Dto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchUpdateVendorResponseV2Dto'
        '400':
          description: Bad Request Error - Thrown if fields sent via query does not follow specifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400ResponseDtoV2'
        '401':
          description: Unauthorized - Not logged in or log in expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401ResponseDto'
        '403':
          description: Forbidden - Not enough permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403ResponseDto'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500ResponseDto'
      security:
      - bearer: []
      summary: Batch Update Vendors
      tags:
      - VendorControllerV2
  /v2/accounting/vendors/{id}:
    put:
      description: '**Supported for:**


        `freshbooks` `quickbooks` `xero` `oracleNetsuite` `sageBusinessCloud` `sageIntacct` `dynamicsBusinessCentral` `myob` `zohoBooks`'
      operationId: put-vendor
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushUpdateVendorV2Dto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutVendorV2ResponseDto'
        '400':
          description: Bad Request Error - Thrown if fields sent via query does not follow specifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400ResponseDtoV2'
        '401':
          description: Unauthorized - Not logged in or log in expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401ResponseDto'
        '403':
          description: Forbidden - Not enough permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403ResponseDto'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500ResponseDto'
      security:
      - bearer: []
      summary: Update a Vendor
      tags:
      - VendorControllerV2
  /v2/accounting/vendors/bankAccounts:
    get:
      description: '**Supported for:**


        `quickbooks` `xero` `sageBusinessCloud` `sageIntacct` `dynamicsBusinessCentral` `dynamics365Finance` `myob`'
      operationId: vendors-bankAccounts
      parameters:
      - name: connectionUuid
        required: true
        in: query
        description: Unique connection identifier.
        schema:
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
          type: string
      - name: offset
        required: false
        in: query
        description: The offset is the position in the dataset of a particular record.
        schema:
          format: integer
          type: number
      - name: limit
        required: false
        in: query
        description: 'This is the size of the results set you would like (default: 100).'
        schema:
          format: integer
          example: 100
          type: number
      - name: orderBy
        required: false
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVendorBankAccountResponseV2Dto'
        '202':
          description: Data in pending state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVendorBankAccountResponseV2Dto'
        '204':
          description: No data available
        '400':
          description: Bad Request Error - Thrown if fields sent via query does not follow specifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400ResponseDtoV2'
        '401':
          description: Unauthorized - Not logged in or log in expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401ResponseDto'
        '403':
          description: Forbidden - Not enough permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403ResponseDto'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500ResponseDto'
      security:
      - bearer: []
      summary: List Vendor Bank Accounts
      tags:
      - VendorControllerV2
    post:
      description: '**Supported for:**


        `quickbooks` `xero` `sageBusinessCloud` `sageIntacct` `dynamicsBusinessCentral` `myob`'
      operationId: push-vendors-bankAccounts
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushVendorBankAccountDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PushVendorBankAccountResponseDto'
        '400':
          description: Bad Request Error - Thrown if fields sent via query does not follow specifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400ResponseDtoV2'
        '401':
          description: Unauthorized - Not logged in or log in expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401ResponseDto'
        '403':
          description: Forbidden - Not enough permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403ResponseDto'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500ResponseDto'
      security:
      - bearer: []
      summary: Create a Vendor Bank Account
      tags:
      - VendorControllerV2
  /v2/accounting/vendors/bankAccounts/{id}:
    put:
      description: '**Supported for:**


        `xero` `sageIntacct` `myob`'
      operationId: put-vendors-bankAccounts
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutVendorBankAccountDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutVendorBankAccountResponseDto'
        '400':
          description: Bad Request Error - Thrown if fields sent via query does not follow specifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400ResponseDtoV2'
        '401':
          description: Unauthorized - Not logged in or log in expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401ResponseDto'
        '403':
          description: Forbidden - Not enough permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403ResponseDto'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500ResponseDto'
      security:
      - bearer: []
      summary: Update a Vendor Bank Account
      tags:
      - VendorControllerV2
components:
  schemas:
    Error403ResponseDto:
      type: object
      properties:
        error:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/Error403Dto'
        payload:
          type: object
          readOnly: true
          example: {}
      required:
      - error
      - payload
    Error401Dto:
      type: object
      properties:
        statusCode:
          type: number
          readOnly: true
          example: 401
        message:
          readOnly: true
          example:
          - Unauthorized
          type: array
          items:
            type: string
        error:
          type: string
          readOnly: true
          example: Unauthorized
      required:
      - statusCode
      - message
      - error
    UpdateVendorIndividualResponseV2Dto:
      type: object
      properties:
        pushCommunicationId:
          type: string
          readOnly: true
          example: 60473b57f0cdd1683ca71f60
        requestedOn:
          type: string
          readOnly: true
          example: '2021-03-09T08:15:22.035Z'
          format: date-time
        status:
          type: string
          readOnly: true
          example: pending
          enum:
          - success
          - failed
          - pending
        data:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/BatchPutVendor'
      required:
      - pushCommunicationId
      - requestedOn
      - status
      - data
    Error401ResponseDto:
      type: object
      properties:
        error:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/Error401Dto'
        payload:
          type: object
          readOnly: true
          example: {}
      required:
      - error
      - payload
    PushVendorBankAccountResponseDto:
      type: object
      properties:
        connectionUuid:
          type: string
          readOnly: true
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        businessName:
          type: string
          readOnly: true
          example: Railz
        serviceName:
          type: string
          readOnly: true
          example: xero
          enum:
          - freshbooks
          - quickbooks
          - quickbooksDesktop
          - xero
          - oracleNetsuite
          - sageBusinessCloud
          - sageIntacct
          - dynamicsBusinessCentral
          - dynamics365Finance
          - wave
          - myob
          - zohoBooks
          - byod
        pushCommunicationId:
          type: string
          readOnly: true
          example: 60473b57f0cdd1683ca71f60
        requestedOn:
          type: string
          readOnly: true
          example: '2021-03-09T08:15:22.035Z'
          format: date-time
        status:
          type: string
          readOnly: true
          example: pending
          enum:
          - success
          - failed
          - pending
        data:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/PushVendorBankAccount'
      required:
      - connectionUuid
      - businessName
      - serviceName
      - pushCommunicationId
      - requestedOn
      - status
      - data
    PushVendorV2Dto:
      type: object
      properties:
        connectionUuid:
          type: string
          description: Unique connection identifier.
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        data:
          $ref: '#/components/schemas/PushVendorV2'
      required:
      - connectionUuid
      - data
    PaginationMetaData:
      type: object
      properties:
        offset:
          type: number
          readOnly: true
        limit:
          type: number
          readOnly: true
        count:
          type: number
          readOnly: true
      required:
      - offset
      - limit
      - count
    PushVendorV2:
      type: object
      properties:
        contactFirstName:
          type: string
          maxLength: 100
          example: Jane
        contactLastName:
          type: string
          maxLength: 100
          example: Smith
        emailAddress:
          type: string
          maxLength: 100
          example: email@acme.com
        phone:
          type: string
          maxLength: 30
          example: '8889990000'
        website:
          type: string
          maxLength: 100
          format: uri
          example: www.acme.com
        isPerson:
          type: boolean
        vendorName:
          type: string
          maxLength: 500
          example: ACME Inc.
        contactName:
          type: string
          maxLength: 500
          example: Jane Smith
        parentRef:
          $ref: '#/components/schemas/ParentRefDto'
        currency:
          type: string
          example: CAD
        paymentMethodRef:
          $ref: '#/components/schemas/PaymentMethodRefDto'
        billingAddress:
          $ref: '#/components/schemas/BillingAddressDto'
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddressDto'
        subsidiaryRefs:
          type: array
          items:
            $ref: '#/components/schemas/SubsidiaryRefDto'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/PushCustomerVendorContactV2'
        taxNumber:
          type: string
          example: '987654321'
        passThrough:
          type: object
          example:
            CustomField:
            - DefinitionId: '1'
              StringValue: my custom value
              Name: Field One
          additionalProperties: true
    PushVendorBankAccountDto:
      type: object
      properties:
        connectionUuid:
          type: string
          description: Unique connection identifier.
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        data:
          $ref: '#/components/schemas/PushVendorBankAccount'
      required:
      - connectionUuid
      - data
    PutVendorBankAccountDto:
      type: object
      properties:
        connectionUuid:
          type: string
          description: Unique connection identifier.
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        data:
          $ref: '#/components/schemas/PutVendorBankAccount'
      required:
      - connectionUuid
      - data
    Error500Dto:
      type: object
      properties:
        error:
          type: string
          readOnly: true
          example: Internal Server Error
        message:
          readOnly: true
          example:
          - INTERNAL_ERROR
          type: array
          items:
            type: string
        statusCode:
          type: number
          readOnly: true
          example: 500
      required:
      - error
      - message
      - statusCode
    PutVendorV2:
      type: object
      properties:
        contactFirstName:
          type: string
          maxLength: 100
          example: Jane
        contactLastName:
          type: string
          maxLength: 100
          example: Smith
        emailAddress:
          type: string
          maxLength: 100
          example: email@acme.com
        phone:
          type: string
          maxLength: 30
          example: '8889990000'
        website:
          type: string
          maxLength: 100
          format: uri
          example: www.acme.com
        isPerson:
          type: boolean
        vendorName:
          type: string
          maxLength: 500
          example: ACME Inc.
        contactName:
          type: string
          example: Jane Smith
        parentRef:
          $ref: '#/components/schemas/ParentRefDto'
        currency:
          type: string
          example: CAD
        paymentMethodRef:
          $ref: '#/components/schemas/PaymentMethodRefDto'
        billingAddress:
          $ref: '#/components/schemas/BillingAddressDto'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/PushCustomerVendorContactV2'
        taxNumber:
          type: string
          example: '987654321'
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddressDto'
        subsidiaryRefs:
          type: array
          items:
            $ref: '#/components/schemas/SubsidiaryRefDto'
        passThrough:
          type: object
          example:
            CustomField:
            - DefinitionId: '1'
              StringValue: my custom value
              Name: Field One
          additionalProperties: true
    PutVendorBankAccount:
      type: object
      properties:
        name:
          type: string
          example: Business Bank Account
        type:
          type: string
          example: checking
        accountNumber:
          type: string
          example: '11200'
        routingNumber:
          type: string
          example: '123456789'
        bankName:
          type: string
          example: TD Bank
        supportsAch:
          type: boolean
          example: true
        supportsWire:
          type: boolean
          example: true
        supportsCheck:
          type: boolean
          example: true
        address:
          $ref: '#/components/schemas/PushBaseAddress'
        contactName:
          type: string
          maxLength: 500
          example: Jane Smith
        currency:
          type: string
          example: CAD
        vendorRef:
          $ref: '#/components/schemas/VendorRefDto'
    BillingAddressDto:
      type: object
      properties:
        line1:
          type: string
          maxLength: 500
          example: 1234 Park Street
        line2:
          type: string
          maxLength: 500
          example: Suite 1000
        city:
          type: string
          maxLength: 255
          example: Toronto
        region:
          type: string
          maxLength: 255
          example: 'ON'
          description: Region within a country. For example, state name for USA, province name for Canada.
        country:
          type: string
          example: CAN
          description: Country name as 3 ISO alpha-3 characters.
        postalCode:
          type: string
          maxLength: 30
          example: A0B1C2
          description: Postal code. For example, zip code for USA and Canada.
    ShippingAddressDto:
      type: object
      properties:
        line1:
          type: string
          maxLength: 500
          example: 1234 Park Street
        line2:
          type: string
          maxLength: 500
          example: Suite 1000
        city:
          type: string
          maxLength: 255
          example: Toronto
        region:
          type: string
          maxLength: 255
          example: 'ON'
          description: Region within a country. For example, state name for USA, province name for Canada.
        country:
          type: string
          example: CAN
          description: Country name as 3 ISO alpha-3 characters.
        postalCode:
          type: string
          maxLength: 30
          example: A0B1C2
          description: Postal code. For example, zip code for USA and Canada.
    PaymentMethodRefDto:
      type: object
      properties:
        id:
          type: string
          example: '1'
        name:
          type: string
          example: Harmonized sales tax
        type:
          type: string
          example: creditCard
          enum:
          - unknown
          - cash
          - check
          - creditCard
          - debitCard
          - bankTransfer
          - giftCard
          - other
    ParentRefDto:
      type: object
      properties:
        id:
          type: string
          example: '32'
      required:
      - id
    Error400DtoV2:
      type: object
      properties:
        statusCode:
          type: number
          readOnly: true
          example: 400
        message:
          readOnly: true
          example:
          - connectionUuid should not be empty
          type: array
          items:
            type: string
        error:
          type: string
          readOnly: true
          example: Bad Request
      required:
      - statusCode
      - message
      - error
    BatchUpdateVendorV2Dto:
      type: object
      properties:
        connectionUuid:
          type: string
          description: Unique connection identifier.
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        batch:
          type: array
          items:
            $ref: '#/components/schemas/BatchPutVendor'
      required:
      - connectionUuid
      - batch
    BaseAddress:
      type: object
      properties:
        line1:
          type: string
          example: 1234 Park Street
        line2:
          type: string
          example: Suite 1000
        city:
          type: string
          example: Toronto
        region:
          type: string
          example: 'ON'
        country:
          type: string
          example: CAN
        postalCode:
          type: string
          example: A0B1C2
    PushVendorV2ResponseDto:
      type: object
      properties:
        connectionUuid:
          type: string
          readOnly: true
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        businessName:
          type: string
          readOnly: true
          example: Railz
        serviceName:
          type: string
          readOnly: true
          example: xero
          enum:
          - freshbooks
          - quickbooks
          - quickbooksDesktop
          - xero
          - oracleNetsuite
          - sageBusinessCloud
          - sageIntacct
          - dynamicsBusinessCentral
          - dynamics365Finance
          - wave
          - myob
          - zohoBooks
          - byod
        pushCommunicationId:
          type: string
          readOnly: true
          example: 60473b57f0cdd1683ca71f60
        requestedOn:
          type: string
          readOnly: true
          example: '2021-03-09T08:15:22.035Z'
          format: date-time
        status:
          type: string
          readOnly: true
          example: pending
          enum:
          - success
          - failed
          - pending
        data:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/PushVendorV2'
      required:
      - connectionUuid
      - businessName
      - serviceName
      - pushCommunicationId
      - requestedOn
      - status
      - data
    CustomerVendorAddress:
      type: object
      properties:
        line1:
          type: string
          example: 1234 Park Street
        line2:
          type: string
          example: Suite 1000
        city:
          type: string
          example: Toronto
        region:
          type: string
          example: 'ON'
        country:
          type: string
          example: CAN
        postalCode:
          type: string
          example: A0B1C2
        type:
          type: string
          enum:
          - billing
          - shipping
          - other
    GetVendorDataV2:
      type: object
      properties:
        id:
          type: string
          example: '1'
        vendorName:
          type: string
          example: ACME Inc.
        contactName:
          type: string
          example: Jane Smith
        emailAddress:
          type: string
          example: email@acme.com
        website:
          type: string
          example: www.acme.com
        phone:
          type: string
          example: '8889990000'
        taxNumber:
          type: string
          example: '987654321'
        balance:
          type: number
          example: 0
          format: float
        status:
          type: string
          enum:
          - unknown
          - active
          - archived
        subsidiaryRefs:
          type: array
          items:
            $ref: '#/components/schemas/SubsidiaryRef'
        sourceModifiedDate:
          type: string
          example: '2021-03-09T08:49:36.035Z'
        parentRef:
          $ref: '#/components/schemas/ParentRef'
        contactFirstName:
          type: string
          example: Jane
        contactLastName:
          type: string
          example: Smith
        isPerson:
          type: boolean
          example: false
        currency:
          type: string
          example: USD
        billingAddress:
          $ref: '#/components/schemas/BillingAddress'
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddress'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/CustomerVendorContactV2'
        paymentMethodRef:
          $ref: '#/components/schemas/PaymentMethodRefResponse'
      required:
      - id
      - status
    PushVendorIndividualResponseV2Dto:
      type: object
      properties:
        pushCommunicationId:
          type: string
          readOnly: true
          example: 60473b57f0cdd1683ca71f60
        requestedOn:
          type: string
          readOnly: true
          example: '2021-03-09T08:15:22.035Z'
          format: date-time
        status:
          type: string
          readOnly: true
          example: pending
          enum:
          - success
          - failed
          - pending
        data:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/PushVendorV2'
      required:
      - pushCommunicationId
      - requestedOn
      - status
      - data
    PaymentMethodRefResponse:
      type: object
      properties:
        id:
          type: string
          example: '3'
        name:
          type: string
          example: Harmonized sales tax
        type:
          type: string
          example: creditCard
          enum:
          - unknown
          - cash
          - check
          - creditCard
          - debitCard
          - bankTransfer
          - giftCard
          - other
    GetVendorBankAccountDataV2:
      type: object
      properties:
        id:
          type: string
          example: lPNjeW1nR6CDn5okmGQ6hEpMo4lLNoSrzqDje
        name:
          type: string
          example: Business Bank Account
        type:
          type: string
          enum:
          - checking
          - saving
          - creditCard
          - loan
          - investment
          - unknown
          example: checking
        accountNumber:
          type: string
          example: '11200'
        routingNumber:
          type: string
          example: '123456789'
        bankName:
          type: string
          example: TD Bank
        supportsAch:
          type: boolean
          example: true
        supportsWire:
          type: boolean
          example: true
        supportsCheck:
          type: boolean
          example: true
        address:
          $ref: '#/components/schemas/BaseAddress'
        contactName:
          type: string
        vendorRef:
          $ref: '#/components/schemas/VendorRef'
        currency:
          type: string
          example: USD
        sourceModifiedDate:
          type: string
          example: '2021-03-09T08:49:36.035Z'
      required:
      - id
    SubsidiaryRef:
      type: object
      properties:
        id:
          type: string
          example: '1'
        name:
          type: string
          example: Railz Financial
    PushUpdateVendorV2Dto:
      type: object
      properties:
        connectionUuid:
          type: string
          description: Unique connection identifier.
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        data:
          $ref: '#/components/schemas/PutVendorV2'
      required:
      - connectionUuid
      - data
    BillingAddress:
      type: object
      properties:
        line1:
          type: string
          example: 1234 Park Street
        line2:
          type: string
          example: Suite 1000
        city:
          type: string
          example: Toronto
        region:
          type: string
          example: 'ON'
        country:
          type: string
          example: CAN
        postalCode:
          type: string
          example: A0B1C2
    PutVendorBankAccountResponseDto:
      type: object
      properties:
        connectionUuid:
          type: string
          readOnly: true
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        businessName:
          type: string
          readOnly: true
          example: Railz
        serviceName:
          type: string
          readOnly: true
          example: xero
          enum:
          - freshbooks
          - quickbooks
          - quickbooksDesktop
          - xero
          - oracleNetsuite
          - sageBusinessCloud
          - sageIntacct
          - dynamicsBusinessCentral
          - dynamics365Finance
          - wave
          - myob
          - zohoBooks
          - byod
        pushCommunicationId:
          type: string
          readOnly: true
          example: 60473b57f0cdd1683ca71f60
        requestedOn:
          type: string
          readOnly: true
          example: '2021-03-09T08:15:22.035Z'
          format: date-time
        status:
          type: string
          readOnly: true
          example: pending
          enum:
          - success
          - failed
          - pending
        data:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/PutVendorBankAccount'
      required:
      - connectionUuid
      - businessName
      - serviceName
      - pushCommunicationId
      - requestedOn
      - status
      - data
    Error400ResponseDtoV2:
      type: object
      properties:
        error:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/Error400DtoV2'
        payload:
          type: object
          readOnly: true
      required:
      - error
      - payload
    BatchPutVendor:
      type: object
      properties:
        contactFirstName:
          type: string
          maxLength: 100
          example: Jane
        contactLastName:
          type: string
          maxLength: 100
          example: Smith
        emailAddress:
          type: string
          maxLength: 100
          example: email@acme.com
        phone:
          type: string
          maxLength: 30
          example: '8889990000'
        website:
          type: string
          maxLength: 100
          format: uri
          example: www.acme.com
        isPerson:
          type: boolean
        vendorName:
          type: string
          maxLength: 500
          example: ACME Inc.
        contactName:
          type: string
          example: Jane Smith
        parentRef:
          $ref: '#/components/schemas/ParentRefDto'
        currency:
          type: string
          example: CAD
        paymentMethodRef:
          $ref: '#/components/schemas/PaymentMethodRefDto'
        billingAddress:
          $ref: '#/components/schemas/BillingAddressDto'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/PushCustomerVendorContactV2'
        taxNumber:
          type: string
          example: '987654321'
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddressDto'
        subsidiaryRefs:
          type: array
          items:
            $ref: '#/components/schemas/SubsidiaryRefDto'
        passThrough:
          type: object
          example:
            CustomField:
            - DefinitionId: '1'
              StringValue: my custom value
              Name: Field One
          additionalProperties: true
        vendorRef:
          type: string
          description: id of vendor to be updated
      required:
      - vendorRef
    ParentRef:
      type: object
      properties:
        id:
          type: string
          example: '434'
        name:
          type: string
          example: Region
      required:
      - id
    ShippingAddress:
      type: object
      properties:
        line1:
          type: string
          example: 1234 Park Street
        line2:
          type: string
          example: Suite 1000
        city:
          type: string
          example: Toronto
        region:
          type: string
          example: 'ON'
        country:
          type: string
          example: CAN
        postalCode:
          type: string
          example: A0B1C2
    Error403Dto:
      type: object
      properties:
        statusCode:
          type: number
          readOnly: true
          example: 403
        message:
          readOnly: true
          example:
          - Forbidden resource
          type: array
          items:
            type: string
        error:
          type: string
          readOnly: true
          example: Forbidden
      required:
      - statusCode
      - message
      - error
    PushVendorBankAccount:
      type: object
      properties:
        name:
          type: string
          example: Business Bank Account
        type:
          type: string
          example: checking
        accountNumber:
          type: string
          example: '11200'
        routingNumber:
          type: string
          example: '123456789'
        bankName:
          type: string
          example: TD Bank
        supportsAch:
          type: boolean
          example: true
        supportsWire:
          type: boolean
          example: true
        supportsCheck:
          type: boolean
          example: true
        address:
          $ref: '#/components/schemas/PushBaseAddress'
        contactName:
          type: string
          maxLength: 500
          example: Jane Smith
        currency:
          type: string
          example: CAD
        vendorRef:
          $ref: '#/components/schemas/VendorRefDto'
      required:
      - vendorRef
    VendorRef:
      type: object
      properties:
        id:
          type: string
          example: '1'
        name:
          type: string
          example: Home Depot
      required:
      - id
    ListReportMetaDataV2:
      type: object
      properties:
        connectionUuid:
          type: string
          readOnly: true
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        businessName:
          type: string
          readOnly: true
          example: Railz
        serviceName:
          type: string
          readOnly: true
          example: xero
          enum:
          - freshbooks
          - quickbooks
          - quickbooksDesktop
          - xero
          - oracleNetsuite
          - sageBusinessCloud
          - sageIntacct
          - dynamicsBusinessCentral
          - dynamics365Finance
          - wave
          - myob
          - zohoBooks
          - byod
        reportId:
          readOnly: true
          example:
          - 5fad8a342a88364234392fb5
          - 5fad8a342a88364234392fb6
          type: array
          items:
            type: string
        createdAt:
          type: string
          readOnly: true
          example: '2020-11-25T01:02:03Z'
          format: date-time
        updatedAt:
          type: string
          example: '2020-11-30T01:02:03Z'
          format: date-time
          readOnly: false
      required:
      - connectionUuid
      - businessName
      - serviceName
      - reportId
      - createdAt
      - updatedAt
    SubsidiaryRefDto:
      type: object
      properties:
        id:
          type: string
          example: '4'
      required:
      - id
    BatchPushVendorResponseV2Dto:
      type: object
      properties:
        connectionUuid:
          type: string
          readOnly: true
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        businessName:
          type: string
          readOnly: true
          example: Railz
        serviceName:
          type: string
          readOnly: true
          example: xero
          enum:
          - freshbooks
          - quickbooks
          - quickbooksDesktop
          - xero
          - oracleNetsuite
          - sageBusinessCloud
          - sageIntacct
          - dynamicsBusinessCentral
          - dynamics365Finance
          - wave
          - myob
          - zohoBooks
          - byod
        batchId:
          type: string
          readOnly: true
          example: 60473b57f0cdd1683ca71f60
        batch:
          readOnly: true
          type: array
          items:
            $ref: '#/components/schemas/PushVendorIndividualResponseV2Dto'
      required:
      - connectionUuid
      - businessName
      - serviceName
      - batchId
      - batch
    BatchPushVendorV2Dto:
      type: object
      properties:
        connectionUuid:
          type: string
          description: Unique connection identifier.
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        batch:
          type: array
          items:
            $ref: '#/components/schemas/PushVendorV2'
      required:
      - connectionUuid
      - batch
    GetVendorResponseV2Dto:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/PaginationMetaData'
        meta:
          $ref: '#/components/schemas/ListReportMetaDataV2'
        data:
          type: array
          items:
            $ref: '#/components/schemas/GetVendorDataV2'
      required:
      - pagination
      - meta
      - data
    GetVendorBankAccountResponseV2Dto:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/ListReportMetaDataV2'
        pagination:
          $ref: '#/components/schemas/PaginationMetaData'
        data:
          type: array
          items:
            $ref: '#/components/schemas/GetVendorBankAccountDataV2'
      required:
      - meta
      - pagination
      - data
    PushCustomerVendorContactV2:
      type: object
      properties:
        name:
          type: string
          example: John Smith
        email:
          type: string
          example: jsmith@company.com
        phone:
          type: string
          example: '8887779999'
        address:
          $ref: '#/components/schemas/CustomerVendorPushAddressV2'
    CustomerVendorPushAddressV2:
      type: object
      properties:
        line1:
          type: string
          example: 1234 Park Street
        line2:
          type: string
          example: Suite 1000
        city:
          type: string
          example: Toronto
        region:
          type: string
          example: 'ON'
        country:
          type: string
          example: CAN
        postalCode:
          type: string
          example: A0B1C2
        type:
          type: string
          enum:
          - billing
          - shipping
          - other
          example: billing
    VendorRefDto:
      type: object
      properties:
        id:
          type: string
          example: '130'
      required:
      - id
    Error500ResponseDto:
      type: object
      properties:
        error:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/Error500Dto'
        payload:
          type: object
          readOnly: true
      required:
      - error
      - payload
    BatchUpdateVendorResponseV2Dto:
      type: object
      properties:
        connectionUuid:
          type: string
          readOnly: true
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        businessName:
          type: string
          readOnly: true
          example: Railz
        serviceName:
          type: string
          readOnly: true
          example: xero
          enum:
          - freshbooks
          - quickbooks
          - quickbooksDesktop
          - xero
          - oracleNetsuite
          - sageBusinessCloud
          - sageIntacct
          - dynamicsBusinessCentral
          - dynamics365Finance
          - wave
          - myob
          - zohoBooks
          - byod
        batchId:
          type: string
          readOnly: true
          example: 60473b57f0cdd1683ca71f60
        batch:
          readOnly: true
          type: array
          items:
            $ref: '#/components/schemas/UpdateVendorIndividualResponseV2Dto'
      required:
      - connectionUuid
      - businessName
      - serviceName
      - batchId
      - batch
    CustomerVendorContactV2:
      type: object
      properties:
        name:
          type: string
          example: John Smith
        email:
          type: string
          example: jsmith@company.com
        phone:
          type: string
          example: '8887779999'
        address:
          $ref: '#/components/schemas/CustomerVendorAddress'
        status:
          type: string
          enum:
          - unknown
          - active
          - archived
    PutVendorV2ResponseDto:
      type: object
      properties:
        connectionUuid:
          type: string
          readOnly: true
          example: CON-396d5daa-26b2-4979-89b6-cafb2c298155
        businessName:
          type: string
          readOnly: true
          example: Railz
        serviceName:
          type: string
          readOnly: true
          example: xero
          enum:
          - freshbooks
          - quickbooks
          - quickbooksDesktop
          - xero
          - oracleNetsuite
          - sageBusinessCloud
          - sageIntacct
          - dynamicsBusinessCentral
          - dynamics365Finance
          - wave
          - myob
          - zohoBooks
          - byod
        pushCommunicationId:
          type: string
          readOnly: true
          example: 60473b57f0cdd1683ca71f60
        requestedOn:
          type: string
          readOnly: true
          example: '2021-03-09T08:15:22.035Z'
          format: date-time
        status:
          type: string
          readOnly: true
          example: pending
          enum:
          - success
          - failed
          - pending
        data:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/PutVendorV2'
      required:
      - connectionUuid
      - businessName
      - serviceName
      - pushCommunicationId
      - requestedOn
      - status
      - data
    PushBaseAddress:
      type: object
      properties:
        line1:
          type: string
          example: 1234 Park Street
        line2:
          type: string
          example: Suite 1000
        city:
          type: string
          example: Toronto
        region:
          type: string
          example: 'ON'
        country:
          type: string
          example: CAN
        postalCode:
          type: string
          example: A0B1C2
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
